tinyMCE.addI18n('en.jivemacros',{
    unlink : "Unlink",
    add : 'Insert',
    remove : 'Remove',
    properties : 'Settings',
    title : 'Settings',
    presets : 'Presets',
    save: "Save",
    'macro.toc': "Table of Contents",
    'macro.quote': "Quote",
    'macro.user': "User",
    'macro.youtube': "YouTube",
    'macro.youtube.attr.__default_attr': "URL or Video ID",
    'macro.youtube.attr.width': "Width",
    'macro.youtube.attr.height': "Height",
    'macro.emoticon.presets': "Emoticons",
    'macro.code': "Syntax Highlighting",
    'macro.code.presets': "Format",
    'macro.code.attr.__default_attr': "Format",
    'macro.code.preset.plain': "Plain",
    'macro.code.preset.sql': "SQL",
    'macro.code.preset.java': "Java",
    'macro.code.preset.html': "Insert Raw HTML",
    'macro.code.preset.xml': "XML",
    'macro.emoticon.preset.angry': "Angry",
    'macro.emoticon.preset.blush': "Blush",
    'macro.emoticon.preset.confused': "Confused",
    'macro.emoticon.preset.cool': "Cool",
    'macro.emoticon.preset.cry': "Cry",
    'macro.emoticon.preset.devil': "Devil",
    'macro.emoticon.preset.grin': "Grin",
    'macro.emoticon.preset.happy': "Happy",
    'macro.emoticon.preset.laugh': "Laugh",
    'macro.emoticon.preset.love': "Love",
    'macro.emoticon.preset.mischief': "Mischief",
    'macro.emoticon.preset.plain': "Plain",
    'macro.emoticon.preset.sad': "Sad",
    'macro.emoticon.preset.shocked': "Shocked",
    'macro.emoticon.preset.silly': "Silly",
    'macro.emoticon.preset.wink': "Wink",
    'macro.emoticon.preset.info': "Info",
    'macro.emoticon.preset.plus': "Plus",
    'macro.emoticon.preset.minus': "Minus",
    'macro.emoticon.preset.alert': "Alert"
});
